##############################
# CUDA Toolkit インストール
##############################
- name: Download CUDA keyring package
  get_url:
    url: 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb'
    dest: /root/cuda-keyring_1.1-1_all.deb

- name: Install CUDA keyring package
  command: dpkg -i /root/cuda-keyring_1.1-1_all.deb

- name: Update apt repository
  apt:
    update_cache: yes

- name: Install CUDA toolkit
  apt:
    name: "{{ cuda_toolkit }}"
    state: present

##############################
# NVIDIA Driver インストール
##############################
- name: Install NVIDIA Open GPU driver
  apt:
    name: nvidia-open
    state: present

- name: Check NVIDIA GPU status
  command: nvidia-smi
  register: nvidia_smi_output

- name: Display NVIDIA GPU status
  debug:
    var: nvidia_smi_output.stdout

##############################
# 環境変数定義
##############################
- name: Ensure CUDA settings are set in /etc/environment
  template:
    src: templates/environment
    dest: /etc/environment

# NOTE: なぜか PATH だけ /etc/environment に定義した値が反映されないため、明示的にexportする
- name: Check nvcc version
  shell: |
    set -euo pipefail
    export $(cat /etc/environment | grep -v -e "^ *#" -e "^ *$" | xargs)
    nvcc --version
  args:
    executable: /bin/bash

##############################
# nvidia-container-toolkitインストール
##############################
- name: Add NVIDIA GPG key
  shell: |
    set -euo pipefail
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor --yes -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
      sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
      tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  args:
    executable: /bin/bash

- name: Update apt repository
  apt:
    update_cache: yes

- name: Install NVIDIA container toolkit
  apt:
    name: nvidia-container-toolkit
    state: present

- name: Configure NVIDIA container runtime
  command: nvidia-ctk runtime configure --runtime=containerd --set-as-default

- name: Restart containerd
  service:
    name: containerd
    state: restarted