apiVersion: v1
kind: Namespace
metadata:
  name: netshoot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: netshoot
  name: netshoot
spec:
  selector:
    matchLabels:
      app: netshoot
  replicas: 5
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      topologySpreadConstraints:  # ノードに均等にPodを配置する
        - maxSkew: 1  # 1台までの差を許容
          topologyKey: "kubernetes.io/hostname"  # 分散対象のキー (この場合はノードごと)
          whenUnsatisfiable: ScheduleAnyway  # DoNotSchedule
          labelSelector:
            matchLabels:
              app: netshoot
      containers:
        - name: netshoot
          image: nicolaka/netshoot
          command: ["sleep", "infinity"]
          resources:
            limits:
              cpu: "125m"
              memory: "100Mi"
            requests:
              cpu: "125m"
              memory: "100Mi"